### ISSUE TITLE
Allow stacking items from the item display block

### ISSUE THREAD

**Issue by Chailotl** [ModFest/glowcase#31]
When picking up an item from the item display block multiple times, it will not let you stack them. For example if an item display block has 1 iron ingot, clicking on it multiple times with the same stack will not increase the stack count. It would be really nice if it could do this, as the work around is to repeatedly pick up the item then drop it to be able to get another copy

**Comment by TheEpicBlock** [comment]
+1 on this feature!
You can already get unlimited of an item, so it's better to just make that explicit. This also feels way better to use
