### ISSUE TITLE
Item Acceptor Block

### ISSUE THREAD

**Issue by sleepingdragoninn** [ModFest/glowcase#46]
Block that allows items of a specific ID or tag to be directly inserted (via use) by adventure mode players.

Creative players should be able to set
- What item / tag is accepted
- What count is required

The acceptor should have a physical appearance, but also render the stack/tag (use EMI conventions where easy) 

At minimum, the acceptor should destroy the inserted tag and output a redstone pulse. More ideally, the acceptor would have the same blockstates as a hopper, and check for space in the connected inventory to push to before destroying and pulsing.

This should mean an acceptor pointed to a dispenser would instantly dispense the accepted item (e.g. an arrow or boat)

**Comment by Chailotl** [comment]
> The acceptor should have a physical appearance

Do you mean it should look like the dispenser/dropper/observer set of blocks?

> the acceptor would have the same blockstates as a hopper, and check for space in the connected inventory to push to before destroying and pulsing.

Could you explain why you want it to be this way? I understand that the hopper blockstates is to precisely control where the redstone signal is sent (I don't think the ticket acceptors had this feature), but I don't understand why it would be checking for connected inventories

**Comment by sleepingdragoninn** [comment]
So the two use cases are "eat an item, destroying it, in exchange for a redstone pulse"

And "eat an item, pushing it to a connected inventory, in exchange for a redstone pulse"

If connected to a dispenser, this would dispense the accepted item.

**Comment by sleepingdragoninn** [comment]
Also the "physical appearance" thing is just that it should have some kind of model that players can recognize, instead of being invisible like most glowcase blocks.

**Comment by Chailotl** [comment]
> And "eat an item, pushing it to a connected inventory, in exchange for a redstone pulse"

Is the intention behind this to behave like some sort of item filter, particularly in combination with using an item tag?

**Comment by sleepingdragoninn** [comment]
the idea is that it's a safe replacement from being able to actually open something like a dispenser. Boats, minecarts, projectiles for little "cannons" - so yeah kinda like a filter!

**Comment by sleepingdragoninn** [comment]
Also a little more interactive - you drop the item in and it does the pulse for you instead of it being a 2 step process

**Comment by Chailotl** [comment]
Ohhh okay that makes sense! Part of me wonders if that idea should be a separate block, but it would probably share a decent amount of code with the item acceptor so I'll go through with it

It's going to be interesting designing the block's textures in a way that conveys both the redstone pulse and hopper-like item pushing behavior
